global:

scrape_configs:
    -   job_name: 'websites'
        metrics_path: /probe
        params:
            module:
                - https_alive
        static_configs:
            - targets:
                - https://aenon-dynamics.com
                - https://andidittrich.com
        relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: http://webstatus:9115

    -   job_name: 'host-ping'
        metrics_path: /probe
        params:
            module:
                - ping
        static_configs:
            - targets:
                - aenon-dynamics.com
        relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: http://webstatus:9115