version: "3.7"


services:

  traefik:
    image: traefik
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      traefik-ingress:
      ext-ingress:
    volumes:
      - /etc/traefik:/etc/traefik

networks:
  traefik-ingress:
    external: true
  ext-ingress:
    external: true